
import { presets } from './data/presets.js';
import { T, INFO_T } from './data/translations.js';
import { hash32, mulberry32, uniqueNums, todayDMY, parseDMY, displayDate } from './js/generator.js';
function infoTr(k){const lang=$('language')?.value||'en';return (INFO_T[lang]||INFO_T.en)[k]||INFO_T.en[k]||k}
function applyInfoLanguage(){document.querySelectorAll('[data-info-i18n]').forEach(el=>el.textContent=infoTr(el.dataset.infoI18n));document.querySelectorAll('.copy-wallet').forEach(b=>{if(!b.dataset.copied)b.textContent=infoTr('copy')})}
function openInfo(){const o=$('infoOverlay');o.classList.add('open');o.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';applyInfoLanguage()}
function closeInfo(){const o=$('infoOverlay');o.classList.remove('open');o.setAttribute('aria-hidden','true');document.body.style.overflow=''}
async function copyWallet(button){const value=button.dataset.wallet;try{await navigator.clipboard.writeText(value)}catch{const ta=document.createElement('textarea');ta.value=value;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}button.dataset.copied='1';button.textContent=infoTr('copied');setTimeout(()=>{delete button.dataset.copied;button.textContent=infoTr('copy')},1200)}

const $=id=>document.getElementById(id); let currentPreset='6'; let lastResult=null;
function tr(k){return (T[$('language').value]||T.en)[k]||T.en[k]||k}
function renderPresets(){ const wrap=$('presets'); wrap.innerHTML=''; presets.forEach(p=>{const b=document.createElement('button');b.className='chip'+(p.id===currentPreset?' active':'');b.textContent=p.id==='custom'?tr('custom'):p.label;b.onclick=()=>selectPreset(p.id);wrap.appendChild(b)}) }
function selectPreset(id){currentPreset=id; const p=presets.find(x=>x.id===id); if(id!=='custom'){ $('mainCount').value=p.m;$('extraCount').value=p.e;$('mainMax').value=p.mm;$('extraMax').value=p.em } renderPresets()}
function validate(){const m=+$('mainCount').value,mm=+$('mainMax').value,e=+$('extraCount').value,em=+$('extraMax').value;return m>0&&mm>=m&&e>=0&&(e===0||em>=e)&&mm<=99&&em<=99}
function generate(){if(!validate()){alert(tr('invalid'));return} let entered=$('dateInput').value.trim();if(!entered){entered=todayDMY();$('dateInput').value=entered}const parsed=parseDMY(entered);if(!parsed){alert(tr('invalidDate'));$('dateInput').focus();return}const date=parsed.display;$('dateInput').value=date;const m=+$('mainCount').value,mm=+$('mainMax').value,e=+$('extraCount').value,em=+$('extraMax').value,salt=$('salt').value.trim();const seedBase=`${parsed.iso}|${m}|${mm}|${e}|${em}|${salt}`;const main=uniqueNums(m,mm,mulberry32(hash32(seedBase+'|main')));const extra=e?uniqueNums(e,em,mulberry32(hash32(seedBase+'|extra'))):[]; lastResult={date,m,mm,e,em,salt,main,extra,created:new Date().toISOString()};renderResult()}
function resultString(r){return `${displayDate(r.date)} • ${r.m}${r.e?`+${r.e}`:''} • ${r.main.join(', ')}${r.e?' + '+r.extra.join(', '):''}`}
function renderResult(){const r=lastResult;if(!r)return;const balls=r.main.map(n=>`<div class="ball">${n}</div>`).join('');const extra=r.extra.length?`<div class="plus">+</div>${r.extra.map(n=>`<div class="ball extra">${n}</div>`).join('')}`:'';$('resultArea').className='';$('resultArea').innerHTML=`<div class="drawMeta"><span>${displayDate(r.date)}</span><span>${r.m}${r.e?`+${r.e}`:''} • 1–${r.mm}${r.e?` / 1–${r.em}`:''}</span></div><div class="balls">${balls}${extra}</div><div class="resultText" id="resultText">${resultString(r)}</div><div class="actions"><button class="btn secondary" id="copyBtn">${tr('copy')}</button><button class="btn secondary" id="saveBtn">${tr('save')}</button></div>`;$('copyBtn').onclick=copyResult;$('saveBtn').onclick=saveResult}
async function copyResult(){if(!lastResult)return;const txt=resultString(lastResult);try{await navigator.clipboard.writeText(txt)}catch{const ta=document.createElement('textarea');ta.value=txt;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()} const b=$('copyBtn');const old=b.textContent;b.textContent=tr('copied');setTimeout(()=>b.textContent=old,1200)}
function getHistory(){try{return JSON.parse(localStorage.getItem('lottoHistory')||'[]')}catch{return[]}}
function saveResult(){if(!lastResult)return;let h=getHistory();h.unshift(lastResult);h=h.slice(0,30);localStorage.setItem('lottoHistory',JSON.stringify(h));$('saveBtn').textContent=tr('saved');renderHistory()}
function renderHistory(){const h=getHistory();$('historyWrap').hidden=!h.length;const w=$('historyList');w.innerHTML='';h.forEach((r,i)=>{const row=document.createElement('div');row.className='histItem';row.innerHTML=`<div class="histText" title="${resultString(r)}">${resultString(r)}</div><div><button class="btn mini" data-copy="${i}">${tr('copy')}</button> <button class="btn mini" data-del="${i}">${tr('delete')}</button></div>`;w.appendChild(row)});w.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const r=h[+b.dataset.copy];try{await navigator.clipboard.writeText(resultString(r))}catch{} b.textContent=tr('copied');setTimeout(()=>b.textContent=tr('copy'),900)});w.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{h.splice(+b.dataset.del,1);localStorage.setItem('lottoHistory',JSON.stringify(h));renderHistory()})}
function applyLanguage(){document.documentElement.lang=$('language').value;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));renderPresets();if(lastResult)renderResult();renderHistory();applyInfoLanguage();localStorage.setItem('lottoLang',$('language').value)}
function reset(){selectPreset('6');$('salt').value='';$('dateInput').value='';lastResult=null;$('resultArea').className='empty';$('resultArea').innerHTML=`<div class="big">🎱</div><p>${tr('empty')}</p>`}

$('infoBtn').onclick=openInfo;$('infoX').onclick=closeInfo;$('infoClose').onclick=closeInfo;$('infoOverlay').addEventListener('click',e=>{if(e.target===$('infoOverlay'))closeInfo()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('infoOverlay').classList.contains('open'))closeInfo()});document.querySelectorAll('.copy-wallet').forEach(b=>b.onclick=()=>copyWallet(b));
$('generateBtn').onclick=generate;$('resetBtn').onclick=reset;$('language').onchange=applyLanguage;$('themeBtn').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('lottoTheme',next)};$('fullscreenBtn').onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();else await document.exitFullscreen?.()};
['mainCount','mainMax','extraCount','extraMax'].forEach(id=>$(id).addEventListener('input',()=>{currentPreset='custom';renderPresets()}));
$('dateInput').addEventListener('input',e=>{let v=e.target.value.replace(/\D/g,'').slice(0,8);if(v.length>4)v=v.slice(0,2)+'/'+v.slice(2,4)+'/'+v.slice(4);else if(v.length>2)v=v.slice(0,2)+'/'+v.slice(2);e.target.value=v});
(function init(){$('language').value='en';document.documentElement.dataset.theme=localStorage.getItem('lottoTheme')||'dark';$('dateInput').value='';applyLanguage();selectPreset('6');renderHistory()})();
